version: '3.8'

services:
  postgres:
    image: postgres:trixie
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer-admin
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=hydra
    restart: unless-stopped
    networks:
      - postgres-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
